[gateway]
debug = true


[models.mistral]
routing=["ollama_provider"]

[models.mistral.providers.ollama_provider]
type="ollama"
api_base="http://localhost:11434/v1"
model_name="mistral"
api_key_location="none"

[functions.generate_haiku]
type="chat"

[functions.generate_haiku.variants.mistral]
type="chat_completion"
model="mistral"
weight=1.0

# [functions.draft_email]
# type="chat"
# user_schema = "functions/draft_email/user_schema.json"
#
# [functions.draft_email.variants.mistral_email_variant]
# type="chat_completion"
# model="mistral"
# weight=1.0
# system_template="functions/draft_email/mistral_email_variant/system.minijinja"
# user_template="functions/draft_email/mistral_email_variant/user.minijinja"
#
# [metrics.email_draft_accepted]
# type = "boolean"
# optimize = "max"
# level = "inference"
#

